name: Android CI (APK Üretici)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: './sherlock app' # Klasör ismin buysa burası çalışacak

    - name: Build with Gradle
      run: ./gradlew assembleDebug
      working-directory: './sherlock app'

    - name: APK Dosyasını Yükle
      uses: actions/upload-artifact@v4
      with:
        name: SherlockApp-Debug-APK
        path: 'sherlock app/app/build/outputs/apk/debug/app-debug.apk'
